In [1]:
import numpy as np

# 1. NumPy Array Oluşturma

In [2]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [3]:
#Sadece tek tip veri tutulur.
np.array([3.14,4,2,13])

array([ 3.14,  4.  ,  2.  , 13.  ])

In [5]:
np.array(([3.14,4,2,13]), dtype=int)

array([ 3,  4,  2, 13])

In [6]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [7]:
np.ones((3,5), dtype = int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [9]:
np.full((3,3),6)

array([[6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])

In [11]:
#iki sayı arası ritmik artan array
np.arange(0,31,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [14]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [15]:
#Ortalama - Standart sapma verilen matris
np.random.normal(10,4,(3,5))

array([[ 8.01884635, 13.49363966,  5.85214695, 18.02949234, 17.07715824],
       [ 7.87707948, 12.01324349,  7.72907944, 14.49063941, 11.67709596],
       [ 2.66583032,  9.89841201, 10.56646242,  7.41559618, 15.51321589]])

In [19]:
np.random.randint(0,10,(3,5))

array([[1, 9, 9, 8, 9],
       [7, 6, 2, 8, 3],
       [2, 9, 3, 0, 8]])

## Array Özellikleri

* ndim: boyut sayısı
* shape: boyut bilgisi
* size: toplam eleman sayısı
* dtype: array veri tipi

In [26]:
np.random.randint(10, size=(3,5))

array([[8, 0, 3, 1, 5],
       [5, 1, 4, 6, 4],
       [6, 9, 5, 5, 0]])

In [32]:
a = np.random.randint(10, size=(3,5))

In [33]:
a.ndim

2

In [34]:
a.shape

(3, 5)

In [35]:
a.size

15

In [36]:
a.dtype

dtype('int32')

### ReShaping

In [38]:
b = np.arange(1,10)
b

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
b.reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [42]:
b_array = b.reshape((3,3))

In [46]:
print("B vektörünün boyut sayısı: ", b.ndim)
print("B matrisinin boyut sayısı: ", b_array.ndim)


B vektörünün boyut sayısı:  1
B matrisinin boyut sayısı:  2


## Concatenation (Array Birleştirme)

In [47]:
x = np.array([1,2,3])
y = np.array([4,5,6]) 

In [48]:
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [49]:
z = np.array([7,8,9])

In [50]:
np.concatenate([x,y,z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

#### İki Boyutlu Array

In [52]:
a = np.array([[1,2,3],
              [4,5,6]])

In [53]:
b = np.array([[3,2,1],
              [6,5,4]])

In [54]:
np.concatenate([a,b])

array([[1, 2, 3],
       [4, 5, 6],
       [3, 2, 1],
       [6, 5, 4]])

In [56]:
np.concatenate([a,b],axis = 1)

array([[1, 2, 3, 3, 2, 1],
       [4, 5, 6, 6, 5, 4]])

## Splitting

In [57]:
x = np.array([1,2,3,99,99,3,2,1])

In [58]:
np.split(x, [3,5])

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

In [59]:
a,b,c = np.split(x, [3,5])

In [60]:
print(a)
print(b)
print(c)

[1 2 3]
[99 99]
[3 2 1]


#### İki Boyutlu Ayırma

In [61]:
m = np.arange(16).reshape(4,4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [62]:
np.vsplit(m,[2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [63]:
ust,alt = np.vsplit(m,[2])

In [65]:
print(ust)

[[0 1 2 3]
 [4 5 6 7]]


In [66]:
print(alt)

[[ 8  9 10 11]
 [12 13 14 15]]


In [68]:
np.hsplit(m,[1])

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1,  2,  3],
        [ 5,  6,  7],
        [ 9, 10, 11],
        [13, 14, 15]])]

In [69]:
sol, sag =np.hsplit(m,[1])

In [70]:
print(sol)

[[ 0]
 [ 4]
 [ 8]
 [12]]


In [71]:
print(sag)

[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [13 14 15]]


## Sorting

In [89]:
v = np.random.randint(0,25,(13))

In [90]:
v

array([20, 24,  8, 10,  3,  7,  0, 16, 12,  3,  0, 21, 12])

In [91]:
np.sort(v)

array([ 0,  0,  3,  3,  7,  8, 10, 12, 12, 16, 20, 21, 24])

In [92]:
v

array([20, 24,  8, 10,  3,  7,  0, 16, 12,  3,  0, 21, 12])

In [93]:
v.sort()

In [94]:
v

array([ 0,  0,  3,  3,  7,  8, 10, 12, 12, 16, 20, 21, 24])

In [95]:
m = np.random.randint(0,52,(3,3))

In [96]:
m

array([[ 2, 26,  6],
       [13, 17, 22],
       [14, 42, 22]])

In [97]:
np.sort(m,axis=1)

array([[ 2,  6, 26],
       [13, 17, 22],
       [14, 22, 42]])

In [98]:
np.sort(m,axis=0)

array([[ 2, 17,  6],
       [13, 26, 22],
       [14, 42, 22]])

## Indexe Erişmek

In [101]:
m = np.random.randint(54, size=(3,7))
m

array([[34,  0, 47,  9, 20, 18, 43],
       [46, 31,  7, 28, 51, 30,  8],
       [30, 41, 10,  3, 40,  0, 12]])

In [105]:
#51 değerli indexe erişmek için (satır-sütun)
m[1,4]

51

In [107]:
# 0 değerini 13 yapmak istersek
m[0,1]=13
m

array([[34, 13, 47,  9, 20, 18, 43],
       [46, 31,  7, 28, 51, 30,  8],
       [30, 41, 10,  3, 40,  0, 12]])

## İki Boyutlu Matrislerde Slice

In [109]:
m =np.random.randint(10, size=(5,5))
m

array([[7, 2, 6, 7, 9],
       [2, 4, 5, 0, 7],
       [1, 9, 9, 8, 9],
       [6, 5, 8, 3, 9],
       [0, 2, 0, 5, 6]])

In [110]:
m[:,0] #0. sütun

array([7, 2, 1, 6, 0])

In [112]:
m[:,4] #4. sütun

array([9, 7, 9, 9, 6])

In [113]:
m[0,:] #0. satır

array([7, 2, 6, 7, 9])

In [114]:
m[0] #0. satır

array([7, 2, 6, 7, 9])

In [116]:
m[0:2,0:3] #2. satır 3.satıra kadar

array([[7, 2, 6],
       [2, 4, 5]])

In [117]:
m[1:3,0:2]

array([[2, 4],
       [1, 9]])

## Alt Küme Üzerinde İşlem Yapmak

In [118]:
m = np.random.randint(10, size = (5,5))
m

array([[9, 7, 8, 6, 2],
       [8, 1, 6, 8, 6],
       [3, 8, 3, 5, 2],
       [4, 1, 8, 1, 9],
       [3, 8, 9, 1, 0]])

In [119]:
alt_m = m[0:3,0:2].copy()

In [120]:
alt_m

array([[9, 7],
       [8, 1],
       [3, 8]])

In [121]:
alt_m[0,0]=9999
alt_m

array([[9999,    7],
       [   8,    1],
       [   3,    8]])

In [122]:
m

array([[9, 7, 8, 6, 2],
       [8, 1, 6, 8, 6],
       [3, 8, 3, 5, 2],
       [4, 1, 8, 1, 9],
       [3, 8, 9, 1, 0]])

## Fancy Index Kullanımı

In [124]:
v= np.arange(0,30,3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [126]:
[v[1],v[3],v[7]]

[3, 9, 21]

In [128]:
#İndexleri listeleyip kullanırsak Fancy index oluyor
indexler = [1,3,7]
v[indexler]

array([ 3,  9, 21])

#### İki Boyutlu Fancy İndex

In [130]:
m= np.random.randint(5,25, size=(3,7))
m

array([[ 7, 19, 16,  8, 18,  9, 16],
       [23, 14,  8, 15, 12, 12, 11],
       [ 6, 17, 12, 16, 18, 10, 12]])

In [133]:
satir = np.array([0,1])
sutun = np.array([1,3])

In [134]:
m[satir,sutun]

array([19, 15])

In [135]:
#Fancy
m[0,[1,2]]

array([19, 16])

In [136]:
#Slice
m[0:, [1,2]]

array([[19, 16],
       [14,  8],
       [17, 12]])

## Koşullu Eleman İşlemleri

In [137]:
v = np.arange(5,22,4)
v

array([ 5,  9, 13, 17, 21])

In [139]:
v < 13

array([ True,  True, False, False, False])

In [140]:
v[v>13]

array([17, 21])

In [142]:
v[v<=13]

array([ 5,  9, 13])

In [143]:
v[v!=17]

array([ 5,  9, 13, 21])

## Operasyonel İşlemler 

In [145]:
v= np.arange(5,62,8)
v

array([ 5, 13, 21, 29, 37, 45, 53, 61])

In [146]:
v*3

array([ 15,  39,  63,  87, 111, 135, 159, 183])

In [147]:
v/4

array([ 1.25,  3.25,  5.25,  7.25,  9.25, 11.25, 13.25, 15.25])

In [148]:
v**2

array([  25,  169,  441,  841, 1369, 2025, 2809, 3721], dtype=int32)

## Matematiksel İşlemler

In [149]:
v

array([ 5, 13, 21, 29, 37, 45, 53, 61])

In [156]:
#çıkarma
np.subtract(v,1)

array([ 4, 12, 20, 28, 36, 44, 52, 60])

In [157]:
#toplama
np.add(v,1)

array([ 6, 14, 22, 30, 38, 46, 54, 62])

In [158]:
#çarpma
np.multiply(v,2)

array([ 10,  26,  42,  58,  74,  90, 106, 122])

In [159]:
#bölme
np.divide(v,3)

array([ 1.66666667,  4.33333333,  7.        ,  9.66666667, 12.33333333,
       15.        , 17.66666667, 20.33333333])

In [160]:
#mod alma
np.mod(v,5)

array([0, 3, 1, 4, 2, 0, 3, 1], dtype=int32)

In [163]:
#kuvvetini alma
np.power(v,3)

array([   125,   2197,   9261,  24389,  50653,  91125, 148877, 226981],
      dtype=int32)

In [164]:
np.absolute(np.array([-3]))

array([3])

In [165]:
np.sin(360)

0.9589157234143065

In [166]:
np.cos(180)

-0.5984600690578581

In [167]:
v = np.array([1,2,3])

In [168]:
np.log2(v)

array([0.       , 1.       , 1.5849625])

In [169]:
np.log10(v)

array([0.        , 0.30103   , 0.47712125])

# 2. Numpy ile İki Bilinmeyenli Denklem Çözümü

4\*x0 + 2\*x1=8 

5\*x0 + 3\*x1=9

In [171]:
a = np.array([[4,2],[5,3]])
b = np.array([8,9])

In [172]:
a

array([[4, 2],
       [5, 3]])

In [173]:
b

array([8, 9])

In [178]:
x = np.linalg.solve(a,b)
x

array([ 3., -2.])

In [183]:
np.arange(0,10, 2)

array([0, 2, 4, 6, 8])